wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [40, 60, 60]
    rows: [10, 10, 10]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        - Auckland: "Pacific/Auckland"
        - Tokyo: "Asia/Tokyo"
        - Beijing: "Asia/Shanghai"
        - Kolkata: "Asia/Kolkata"
        - Berlin: "Europe/Berlin"
        - UTC: "Etc/UTC"
        - New York: "America/New York"
        - Los Angeles: "America/Los_Angeles"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "natural"
      title: "Clocks"
      type: "clocks"
    feedreader:
      enabled: true
      feeds:
      - http://feeds.bbci.co.uk/news/rss.xml
      feedLimit: 10
      position:
        top: 0
        left: 1
        width: 2
        height: 1
      refreshInterval: 14400
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    cmdrunner:
      cmd: "snapper"
      args: ["-c", "root", "list"]
      tail: true
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 2
      refreshInterval: 60
      title: "BTRFS Snapshots"
